definitions:
  main.HTTPError:
    properties:
      error:
        type: string
    type: object
  main.HTTPMessage:
    properties:
      message:
        type: string
    type: object
  main.Recipe:
    properties:
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      name:
        type: string
      publishedAt:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /recipes:
    get:
      consumes:
      - application/json
      description: Returns list of recipes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Recipe'
            type: array
      summary: listRecipes
      tags:
      - recipes
    post:
      consumes:
      - application/json
      description: Add a new recipe
      parameters:
      - description: Add recipe
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/main.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Recipe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
      summary: newRecipe
      tags:
      - recipes
  /recipes/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing recipe
      parameters:
      - description: recipe id
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HTTPMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
      summary: deleteRecipe
      tags:
      - recipes
    put:
      consumes:
      - application/json
      description: Update an existing recipe
      parameters:
      - description: recipe id
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - description: Edit recipe
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/main.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Recipe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
      summary: updateRecipe
      tags:
      - recipes
  /recipes/search:
    get:
      consumes:
      - application/json
      description: Returns search recipes
      parameters:
      - description: recipe search by tag
        format: string
        in: query
        name: tag
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Recipe'
            type: array
      summary: searchRecipes
      tags:
      - recipes
swagger: "2.0"
